/* Browser end-to-end test for Home Base. See tests/README.md.
 *   BASE=http://localhost:8080 PASS='test-passphrase-123' node tests/e2e.cjs
 * Needs Playwright + Chromium and a fresh (seeded) database. */
const path = require('path');
const fs = require('fs');
const os = require('os');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const BASE = process.env.BASE || 'http://localhost:8080';
const PASS = process.env.PASS || 'test-passphrase-123';
const CHROME = process.env.CHROME || undefined;

let failures = 0;
const ok = (cond, msg) => { console.log((cond ? '  ok   ' : '  FAIL ') + msg); if (!cond) failures++; };
const section = (t) => console.log('\n# ' + t);

async function drag(page, from, to, opt = {}) {
  const a = await from.boundingBox(), b = await to.boundingBox();
  const sx = a.x + (opt.fx ?? a.width / 2), sy = a.y + (opt.fy ?? a.height / 2);
  const tx = b.x + (opt.tx ?? b.width / 2), ty = b.y + (opt.ty ?? b.height / 2);
  await page.mouse.move(sx, sy);
  await page.mouse.down();
  await page.mouse.move(sx + 6, sy + 6, { steps: 3 });
  await page.mouse.move(tx, ty, { steps: 14 });
  await page.waitForTimeout(150);
  await page.mouse.move(tx + 1, ty + 1, { steps: 2 });
  await page.mouse.up();
  await page.waitForTimeout(300);
}
const settle = (page) => page.waitForFunction(() => HB.store.status === 'saved' && !HB.store.ops.length, null, { timeout: 8000 });
const tileByType = (page, type, n = 0) => page.locator(`.tile[data-type="${type}"]`).nth(n);

(async () => {
  const browser = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });
  const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 }, acceptDownloads: true });
  const page = await ctx.newPage();
  const errors = [];
  let expect400 = false;
  page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !/401|403|429/.test(m.text()) && !(expect400 && /400/.test(m.text()))) errors.push('console: ' + m.text()); });
  page.on('dialog', (d) => d.accept());

  section('login');
  await page.goto(BASE + '/');
  await page.fill('#pass', 'wrong-pass');
  await page.click('button[type=submit]');
  await page.waitForSelector('#login-msg:not(:empty)');
  ok(/Wrong passphrase/.test(await page.textContent('#login-msg')), 'wrong passphrase is refused with a message');
  await page.fill('#pass', PASS);
  await page.click('button[type=submit]');
  await page.waitForSelector('.tile');
  ok((await page.locator('.tab:not(.add)').count()) === 3, '3 scenarios (Work, Idea, PhD) shown as tabs');
  ok((await page.locator('.tile').count()) >= 4, 'Work scenario draws its seeded tiles');

  section('toolbox links');
  const tb = tileByType(page, 'toolbox');
  await tb.locator('input[data-key="link-add"]').fill('Example Site | example.com');
  await tb.locator('input[data-key="link-add"]').press('Enter');
  await tb.locator('.link-card').first().waitFor();
  await tb.locator('input[data-key="link-add"]').fill('https://wikipedia.org');
  await tb.locator('input[data-key="link-add"]').press('Enter');
  await page.waitForFunction(() => document.querySelectorAll('.tile[data-type="toolbox"] .link-card').length === 2);
  ok(await tb.locator('.link-card').first().getAttribute('href') === 'https://example.com', 'quick-add normalises a bare domain to https');
  await tb.locator('input[data-key="link-add"]').fill('javascript:alert(1)');
  await tb.locator('input[data-key="link-add"]').press('Enter');
  await page.waitForTimeout(300);
  ok((await tb.locator('.link-card').count()) === 2, 'javascript: links are rejected');
  await drag(page, tb.locator('.link-card').nth(1), tb.locator('.link-card').nth(0), { fy: 5, ty: 3 });
  await settle(page);
  ok((await tb.locator('.link-card .link-name').first().textContent()) === 'wikipedia.org', 'dragging a link reorders it');

  section('to-do buckets');
  const td = tileByType(page, 'todo');
  for (const [b, t] of [['urgent', 'Write the report #work'], ['urgent', 'Email supervisor'], ['later', 'Plan holiday']]) {
    const inp = td.locator(`input[data-key="task-${b}"]`);
    await inp.fill(t);
    await inp.press('Enter');
    await page.waitForFunction((x) => [...document.querySelectorAll('.task-text')].some((e) => e.textContent === x), t);
  }
  ok((await td.locator('.bucket[data-bucket="urgent"] .task').count()) === 2, 'tasks land in the right bucket');
  ok((await td.locator('.chip').first().textContent()) === '#work', '#hashtags in a task become tags');
  await td.locator('.bucket[data-bucket="urgent"] .task-check').first().check();
  await settle(page);
  ok((await td.locator('.task.done').count()) === 1, 'ticking marks a task done');
  await drag(page, td.locator('.bucket[data-bucket="urgent"] .task').nth(1), td.locator('.bucket[data-bucket="later"] .tasks'), { fx: 60 });
  await settle(page);
  ok((await td.locator('.bucket[data-bucket="later"] .task').count()) === 2, 'dragging a task to Later moves it');

  section('thought dump + clock');
  const th = tileByType(page, 'thoughts');
  await th.locator('textarea[data-key="thought"]').fill('First idea about #phd');
  await th.locator('textarea[data-key="thought"]').press('Enter');
  await th.locator('.thought').first().waitFor();
  ok(/\d/.test(await th.locator('.thought-time').first().textContent()), 'thoughts are timestamped');
  ok(/\d{2}:\d{2}/.test(await tileByType(page, 'clock').locator('.clock-time').textContent()), 'clock shows the time');

  section('persistence across reload');
  await settle(page);
  await page.reload();
  await page.waitForSelector('.task');
  ok((await page.locator('.bucket[data-bucket="later"] .task').count()) === 2, 'task dragged to Later is still there after reload');
  ok((await page.locator('.tile[data-type="toolbox"] .link-card .link-name').first().textContent()) === 'wikipedia.org', 'link order survives reload');
  ok((await page.locator('.thought').count()) === 1, 'thought survives reload');

  section('sync + instant load');
  await page.evaluate(async () => {   // pretend another device added a task straight through the API
    const t = HB.store.tilesOf(HB.app.scenarioId).find((x) => x.type === 'todo');
    await HB.api.batch([{ op: 'create', type: 'tasks', data: { tile_id: t.id, bucket: 'brainoff', text: 'Added from another device' } }]);
  });
  await page.evaluate(() => HB.store.sync());
  await page.waitForFunction(() => [...document.querySelectorAll('.task-text')].some((e) => e.textContent === 'Added from another device'), null, { timeout: 5000 });
  ok(true, 'a change made on another device shows up after a sync (tab focus / every 30 s)');
  await page.route('**/api.php?r=state', (route) => new Promise((res) => setTimeout(() => { route.continue().then(res, res); }, 2500)));
  const t0 = Date.now();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForSelector('.tile .task-text', { timeout: 2000 });
  ok(Date.now() - t0 < 2400, 'the page draws from the local cache before the network answers');
  await page.unroute('**/api.php?r=state');
  await page.waitForTimeout(3200);
  await settle(page);

  section('grid: move + resize persist');
  const before = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).map((t) => ({ id: t.id, x: t.x, y: t.y, w: t.width, h: t.height, type: t.type })));
  const clockTile = tileByType(page, 'clock');
  const box = await clockTile.boundingBox();
  const grab = await page.locator('.tile[data-type="clock"] .tile-head').boundingBox();
  await page.mouse.move(grab.x + 60, grab.y + 14);
  await page.mouse.down();
  await page.mouse.move(grab.x + 80, grab.y + 40, { steps: 4 });
  await page.mouse.move(grab.x + 60, grab.y + 380, { steps: 12 });
  await page.mouse.up();
  await settle(page);
  const afterMove = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'clock'));
  ok(afterMove.y !== before.find((t) => t.type === 'clock').y || afterMove.x !== before.find((t) => t.type === 'clock').x, 'dragging a tile by its title moves it');
  await page.waitForTimeout(700); // let the grid finish animating
  const tb2 = await page.locator('.tile[data-type="thoughts"]').boundingBox();
  const bl = { x: tb2.x + tb2.width - 3, y: tb2.y + tb2.height - 3 };
  const th0 = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  await page.mouse.move(bl.x - 30, bl.y - 30);
  await page.waitForTimeout(150);
  await page.mouse.move(bl.x, bl.y);
  await page.waitForTimeout(150);
  await page.mouse.down();
  await page.mouse.move(bl.x + 40, bl.y + 30, { steps: 5 });
  await page.mouse.move(bl.x + 250, bl.y + 150, { steps: 12 });
  await page.mouse.up();
  await settle(page);
  const th1 = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  ok(th1.width > th0.width || th1.height > th0.height, `dragging a corner resizes a tile (${th0.width}x${th0.height} → ${th1.width}x${th1.height})`);
  await page.reload();
  await page.waitForSelector('.tile');
  const persisted = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  ok(persisted.width === th1.width && persisted.height === th1.height, 'layout survives a reload (from the server, not only the cache)');
  const fromServer = await page.evaluate(async () => (await HB.api.state()).tiles.find((t) => t.type === 'thoughts'));
  ok(fromServer.width === th1.width, 'server holds the new size');

  section('undo');
  await page.waitForTimeout(700);
  const tb3 = await page.locator('.tile[data-type="thoughts"]').boundingBox();
  const u0 = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  await page.mouse.move(tb3.x + tb3.width - 30, tb3.y + tb3.height - 30);
  await page.waitForTimeout(150);
  await page.mouse.move(tb3.x + tb3.width - 3, tb3.y + tb3.height - 3);
  await page.waitForTimeout(150);
  await page.mouse.down();
  await page.mouse.move(tb3.x + tb3.width - 60, tb3.y + tb3.height - 40, { steps: 5 });
  await page.mouse.move(tb3.x + tb3.width - 200, tb3.y + tb3.height - 140, { steps: 10 });
  await page.mouse.up();
  await settle(page);
  const u1 = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  ok(u1.width < u0.width || u1.height < u0.height, `shrinking a tile works (${u0.width}x${u0.height} → ${u1.width}x${u1.height})`);
  await page.keyboard.press('Control+z');
  await settle(page);
  const undone = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  ok(undone.width === u0.width && undone.height === u0.height, 'Ctrl+Z reverses the resize');
  const undoneServer = await page.evaluate(async () => (await HB.api.state()).tiles.find((t) => t.type === 'thoughts'));
  ok(undoneServer.width === u0.width && undoneServer.height === u0.height, 'the undo was saved to the server too');
  await page.keyboard.press('Control+Shift+z');
  await settle(page);
  const redone = await page.evaluate(() => HB.store.tilesOf(HB.app.scenarioId).find((t) => t.type === 'thoughts'));
  ok(redone.width === u1.width && redone.height === u1.height, 'Ctrl+Shift+Z redoes it');

  section('trash: drag tile to trash, restore');
  const nTiles = await page.locator('.tile').count();
  const clk = page.locator('.tile[data-type="clock"] .tile-head');
  await drag(page, clk, page.locator('#trash-zone'), { fx: 80 });
  await settle(page);
  ok((await page.locator('.tile').count()) === nTiles - 1, 'dropping a tile on Trash deletes it');
  await page.waitForFunction(() => document.getElementById('trash-count').textContent === '1', null, { timeout: 5000 });
  await page.click('#trash-zone');
  await page.waitForSelector('.trash-row');
  ok(/Clock/.test(await page.textContent('.trash-row')), 'the deleted tile is listed in the trash');
  await page.click('.trash-row .btn:has-text("Restore")');
  await page.waitForTimeout(500);
  await page.keyboard.press('Escape');
  await page.waitForFunction((n) => document.querySelectorAll('.tile').length === n, nTiles, { timeout: 5000 });
  ok(true, 'restoring brings the tile back');
  section('trash: drag a task to trash');
  await drag(page, td.locator('.bucket[data-bucket="later"] .task').first(), page.locator('#trash-zone'), { fx: 60 });
  await settle(page);
  ok((await td.locator('.bucket[data-bucket="later"] .task').count()) === 1, 'dragging a task to Trash removes it');
  await page.keyboard.press('Control+z');
  await page.waitForTimeout(400);
  ok((await td.locator('.bucket[data-bucket="later"] .task').count()) === 2, 'Ctrl+Z brings the deleted task back');

  section('scenarios');
  await page.keyboard.press('2');
  await page.waitForFunction(() => HB.app.scenarioId === HB.store.scenarios()[1].id);
  ok((await page.locator('.tab.active').textContent()) === 'Idea', 'key 2 switches to Idea');
  ok((await page.locator('.tile[data-type="todo"]').count()) === 0, 'Idea keeps its own tiles');
  await page.click('.tab.add');
  await page.fill('.modal input', 'Reading');
  await page.press('.modal input', 'Enter');
  await page.waitForSelector('.tab:has-text("Reading")');
  ok(true, 'a new scenario can be added');
  await page.locator('.tab:has-text("Reading")').dblclick();
  await page.fill('.tab .inline-edit', 'Reading list');
  await page.press('.tab .inline-edit', 'Enter');
  await page.waitForSelector('.tab:has-text("Reading list")');
  ok(true, 'a scenario can be renamed in place');
  await page.click('#btn-add');
  await page.click('.menu-item:has-text("Countdown")');
  await page.waitForSelector('.tile[data-type="countdown"]');
  await page.click('.tile[data-type="countdown"] .add-cd');
  await page.fill('.modal input[type=text]', 'Thesis');
  const future = new Date(Date.now() + 10 * 86400000);
  const ds = `${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-${String(future.getDate()).padStart(2, '0')}`;
  await page.fill('.modal input[type=date]', ds);
  await page.click('.modal .btn.primary');
  await page.waitForSelector('.cd');
  ok(/^10/.test((await page.textContent('.cd .cd-days')).trim()), 'countdown shows 10 days left');
  await settle(page);
  await page.keyboard.press('1');

  section('files: upload, preview, download, rename, move');
  await page.click('#btn-add');
  await page.click('.menu-item:has-text("Files")');
  await page.waitForSelector('.tile[data-type="files"]');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hb-'));
  const small = path.join(dir, 'notes.txt'); fs.writeFileSync(small, 'hello home base\n');
  const big = path.join(dir, 'big-data.bin'); const bigBuf = require('crypto').randomBytes(5 * 1024 * 1024 + 123); fs.writeFileSync(big, bigBuf);
  const bigHash = require('crypto').createHash('sha256').update(bigBuf).digest('hex');
  const png = path.join(dir, 'pic.png');
  fs.writeFileSync(png, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64'));
  await page.setInputFiles('.tile[data-type="files"] input[type=file]', [small, big, png]);
  await page.waitForFunction(() => document.querySelectorAll('.tile[data-type="files"] .file').length === 3, null, { timeout: 30000 });
  ok(true, 'small file, 5 MB file (chunked) and image all uploaded');
  const limits = await page.evaluate(() => HB.store.data.limits);
  ok(limits.chunk > 0 && 5 * 1024 * 1024 > limits.single_max, `5 MB exceeds the single-request limit (${limits.single_max}) so it used chunks of ${limits.chunk}`);
  const sizes = await page.evaluate(() => HB.store.data.files.map((f) => f.size).sort((a, b) => a - b));
  ok(sizes.includes(5 * 1024 * 1024 + 123), 'chunked file stored with the exact size');
  const bigRow = await page.evaluate(() => HB.store.data.files.find((f) => f.original_name === 'big-data.bin'));
  const dl = await page.evaluate(async (id) => { const r = await fetch('file.php?id=' + id + '&dl=1'); const b = await r.arrayBuffer(); const h = await crypto.subtle.digest('SHA-256', b); return { len: b.byteLength, hash: Array.from(new Uint8Array(h), (x) => x.toString(16).padStart(2, '0')).join(''), cd: r.headers.get('content-disposition') }; }, bigRow.id);
  ok(dl.len === 5 * 1024 * 1024 + 123 && dl.hash === bigHash, 'downloaded bytes match the upload exactly (SHA-256)');
  ok(/attachment/.test(dl.cd), 'download is served as attachment');
  const range = await page.evaluate(async (id) => { const r = await fetch('file.php?id=' + id, { headers: { Range: 'bytes=10-19' } }); return { s: r.status, n: (await r.arrayBuffer()).byteLength, cr: r.headers.get('content-range') }; }, bigRow.id);
  ok(range.s === 206 && range.n === 10, 'Range requests work (needed for audio seeking)');
  await page.locator('.file:has-text("notes.txt") .file-name').click();
  await page.waitForSelector('.modal .preview-text');
  await page.waitForFunction(() => /hello home base/.test(document.querySelector('.preview-text').textContent));
  ok(true, 'text file previews inside the app');
  await page.keyboard.press('Escape');
  await page.locator('.file:has-text("notes.txt")').click({ button: 'right' });
  await page.click('.menu-item:has-text("Rename")');
  await page.fill('.file .inline-edit', 'renamed.txt');
  await page.press('.file .inline-edit', 'Enter');
  await page.waitForSelector('.file:has-text("renamed.txt")');
  await settle(page);
  ok(true, 'file renamed');
  // add a second files tile and drag a file across
  await page.click('#btn-add'); await page.click('.menu-item:has-text("Files")');
  await page.waitForFunction(() => document.querySelectorAll('.tile[data-type="files"]').length === 2);
  await page.waitForTimeout(500);
  await drag(page, page.locator('.tile[data-type="files"]').nth(0).locator('.file:has-text("renamed.txt")'), page.locator('.tile[data-type="files"]').nth(1).locator('.files'), { fx: 80 });
  await settle(page);
  await page.waitForTimeout(300);
  ok((await page.locator('.tile[data-type="files"]').nth(1).locator('.file').count()) === 1, 'dragging a file to another Files tile moves it');
  await page.reload();
  await page.waitForSelector('.tile[data-type="files"] .file');
  ok((await page.locator('.file:has-text("renamed.txt")').count()) === 1, 'renamed + moved file survives reload');
  const thumb = await page.locator('.file:has-text("pic.png") img.thumb').evaluate((i) => i.complete && i.naturalWidth > 0);
  ok(thumb, 'image thumbnails load through the gateway');

  section('music');
  await page.click('#btn-add'); await page.click('.menu-item:has-text("Music")');
  await page.waitForSelector('.tile[data-type="music"]');
  const wav = path.join(dir, 'tone.wav');
  const rate = 8000, n = rate * 2, buf = Buffer.alloc(44 + n * 2);
  buf.write('RIFF', 0); buf.writeUInt32LE(36 + n * 2, 4); buf.write('WAVEfmt ', 8); buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22);
  buf.writeUInt32LE(rate, 24); buf.writeUInt32LE(rate * 2, 28); buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34); buf.write('data', 36); buf.writeUInt32LE(n * 2, 40);
  for (let i = 0; i < n; i++) buf.writeInt16LE(Math.round(Math.sin(i / 8) * 8000), 44 + i * 2);
  fs.writeFileSync(wav, buf);
  await page.setInputFiles('.tile[data-type="music"] input[type=file]', [wav]);
  await page.waitForSelector('.tile[data-type="music"] .file');
  await page.click('.tile[data-type="music"] .mp-play');
  await page.waitForFunction(() => !document.getElementById('audio').paused, null, { timeout: 5000 });
  ok(/tone/.test(await page.textContent('.tile[data-type="music"] .mp-title')), 'music tile plays an uploaded track');
  await page.click('.tile[data-type="music"] .mp-play');
  ok(await page.evaluate(() => document.getElementById('audio').paused), 'pause works');
  // non-audio refused for music tile
  expect400 = true;
  const rej = await page.evaluate(async () => { const f = new FormData(); f.append('tile_id', HB.store.data.tiles.find((t) => t.type === 'music').id); f.append('file', new Blob(['x']), 'a.txt'); const r = await fetch('api.php?r=upload', { method: 'POST', headers: { 'X-CSRF-Token': HB.api.csrf() }, body: f }); return r.status; });
  expect400 = false;
  ok(rej === 400, 'server refuses non-audio files for a music tile');

  section('search + command bar');
  await page.keyboard.press('Control+k');
  await page.fill('.cmd-input', 'wikipedia');
  await page.waitForSelector('.cmd-row:has-text("wikipedia")');
  ok(true, 'Ctrl+K finds a link by name');
  await page.fill('.cmd-input', 'phd');
  await page.waitForSelector('.cmd-row:has-text("First idea")');
  ok(true, 'search finds a thought by its tag');
  await page.keyboard.press('Escape');

  section('shared tile across scenarios');
  await page.locator('.tile[data-type="todo"] .tile-btn').first().click();
  await page.click('.menu-item:has-text("Also show in")');
  await page.locator('.menu.sub .menu-item:has-text("PhD")').click();
  await settle(page);
  await page.keyboard.press('3');
  await page.waitForSelector('.tile.mirror');
  ok((await page.locator('.tile.mirror .task').count()) >= 3, 'the shared to-do tile shows the same tasks in PhD');

  section('theme, backup, mobile');
  await page.click('#btn-menu');
  await page.click('.menu-item:has-text("Theme")');
  await page.locator('.menu.sub .menu-item:has-text("Dark")').click();
  ok((await page.evaluate(() => document.documentElement.dataset.theme)) === 'dark', 'dark mode applies');
  await settle(page);
  const exp = await page.evaluate(async () => { const r = await fetch('export.php?format=json'); const j = await r.json(); return { s: r.status, tiles: j.tiles.length, files: j.files.length }; });
  ok(exp.s === 200 && exp.tiles > 5 && exp.files === 4, 'JSON backup contains tiles and file records');
  const zip = await page.evaluate(async () => { const r = await fetch('export.php?format=zip'); const b = new Uint8Array(await r.arrayBuffer()); return { s: r.status, magic: String.fromCharCode(b[0], b[1]), len: b.length }; });
  ok(zip.s === 200 && zip.magic === 'PK' && zip.len > 5 * 1024 * 1024, 'zip backup includes the uploaded files');
  const m = await browser.newContext({ viewport: { width: 390, height: 800 }, hasTouch: true });
  const mp = await m.newPage();
  await mp.goto(BASE + '/'); await mp.fill('#pass', PASS); await mp.click('button[type=submit]');
  await mp.waitForSelector('.mobile-list .tile');
  ok(true, 'phone width uses the stacked layout');
  await mp.screenshot({ path: path.join(os.tmpdir(), 'hb-mobile.png') });
  const order0 = await mp.$$eval('.mobile-list .tile-wrap', (e) => e.map((x) => x.dataset.tile));
  const h0 = await mp.locator('.mobile-list .tile-wrap').nth(0).locator('.tile-head').boundingBox();
  const h1 = await mp.locator('.mobile-list .tile-wrap').nth(1).boundingBox();
  await mp.mouse.move(h0.x + 60, h0.y + 14); await mp.mouse.down();
  await mp.mouse.move(h0.x + 62, h0.y + 24, { steps: 3 });
  await mp.mouse.move(h0.x + 60, Math.min(h1.y + h1.height - 10, 770), { steps: 12 }); // keep the target inside the 800 px viewport
  await mp.mouse.up();
  await mp.waitForFunction(() => HB.store.status === 'saved' && !HB.store.ops.length);
  const order1 = await mp.$$eval('.mobile-list .tile-wrap', (e) => e.map((x) => x.dataset.tile));
  if (order1[0] === order0[0]) console.log('   debug', JSON.stringify({ order0, order1, h0, h1, active: await mp.evaluate(() => HB.drag.active) }));
  ok(order1[0] !== order0[0], 'on a phone, tiles can be reordered by dragging their title');
  await mp.reload();
  await mp.waitForSelector('.mobile-list .tile');
  ok(JSON.stringify(await mp.$$eval('.mobile-list .tile-wrap', (e) => e.map((x) => x.dataset.tile))) === JSON.stringify(order1), 'the phone order survives a reload');
  await m.close();

  section('security');
  const anon = await browser.newContext();
  const ap = await anon.newPage();
  const r1 = await ap.request.get(BASE + '/api.php?r=state');
  ok(r1.status() === 401, 'API refuses anonymous requests');
  const r2 = await ap.request.get(BASE + '/file.php?id=1');
  ok(r2.status() === 401, 'files are not served without login');
  const r3 = await ap.request.get(BASE + '/api.php?r=batch', { headers: {} });
  ok([401, 403, 405].includes(r3.status()), 'batch endpoint is closed to anonymous');
  const r4 = await page.request.post(BASE + '/api.php?r=batch', { data: { ops: [] } });
  ok(r4.status() === 403, 'writes without the CSRF token are refused even when logged in');
  const r5 = await ap.request.get(BASE + '/.env'); ok([403, 404].includes(r5.status()), '.env is not reachable from the web');
  await anon.close();

  section('logout');
  await page.click('#btn-menu');
  await page.click('.menu-item:has-text("Sign out")');
  await page.waitForSelector('#login-form');
  ok(true, 'sign out returns to the login page');

  ok(errors.length === 0, 'no browser errors' + (errors.length ? ': ' + errors.slice(0, 5).join(' | ') : ''));
  await browser.close();
  console.log(failures ? `\n${failures} FAILED` : '\nALL PASSED');
  process.exit(failures ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
